<?php
$pdo = new PDO('sqlite:tasks.db');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$pdo->exec("CREATE TABLE IF NOT EXISTS TODOLIST (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TITLE TEXT NOT NULL,
  DESCRIPTION TEXT,
  COMPLETED INTEGER DEFAULT 0,   
  IMPORTANT INTEGER DEFAULT 0, 
  TAG TEXT NOT NULL,
  STATUS TEXT DEFAULT 'todo'  
);");